spring:
  application:
    name: TransportHC


  datasource:
    url: "jdbc:mysql://localhost:3306/TransportHC"
    username: root
    password: 1201

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /transport

jwt:
  signerKey: ${SECRET_SIGNER_KEY}