spring:
  application:
    name: TransportHC


  datasource:
    url: "jdbc:mysql://localhost:3306/TransportHC"
    username: root
    password: 1201

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /transport

jwt:
  signerKey: "21a111f344b1b8d9d8868dcd26db4a9a38d4768c00b1270c06974b0774cc8937"